### ISSUE TITLE
大神，创建流程图提示找不到路径什么问题哈？

### ISSUE THREAD

**Issue by langfeng1314** [wanglin2/lx-doc#11]
![image](https://github.com/user-attachments/assets/ee813f26-016b-4b6e-983d-751bffe43408)

![image](https://github.com/user-attachments/assets/c673b89a-253d-485e-bcfb-d8bc49c1d788)

**Comment by wanglin2** [comment]
路径不正确，本地开发的路径是这样的，http://localhost:9097/?id=123&dev=1，线上是这样的，/flowchart/123
