### ISSUE TITLE
前端flowchart模块文件缺少

### ISSUE THREAD

**Issue by helloword-1** [wanglin2/lx-doc#14]
作者你好，其他模块与后端均可以成功运行与使用，但flowchart模块似乎缺少js文件
![image](https://github.com/user-attachments/assets/3de00827-1e86-4a89-8e2b-09fa8339a352)
![image](https://github.com/user-attachments/assets/b2d786bc-88b8-4894-a38e-8f510b4aa7e2)

**Comment by wanglin2** [comment]
可以参考这个文档：https://wanglin2.github.io/lx-doc-site/doc/frontendDev.html#%E6%B5%81%E7%A8%8B%E5%9B%BE%E9%A1%B9%E7%9B%AE

**Comment by helloword-1** [comment]
> 可以参考这个文档：https://wanglin2.github.io/lx-doc-site/doc/frontendDev.html#%E6%B5%81%E7%A8%8B%E5%9B%BE%E9%A1%B9%E7%9B%AE

ok，谢谢作者，已经成功解决了
