### ISSUE TITLE
部署文档还未完善

### ISSUE THREAD

**Issue by 13653216371** [wanglin2/lx-doc#8]
rt

**Comment by wanglin2** [comment]
加上了

**Comment by 13653216371** [comment]
后端用docker的nginx版跑起来了，也把前端挂载进docker了，然后跑起来前端的mind-map，不管是80还是/mind-map都没有页面。。。只有一个title

**Comment by Raikyou** [comment]
> 后端用docker的nginx版跑起来了，也把前端挂载进docker了，然后跑起来前端的mind-map，不管是80还是/mind-map都没有页面。。。只有一个title

怎么把前端和后端一起放在docker里跑，如果有镜像可以分享下吗

**Comment by wanglin2** [comment]
> 后端用docker的nginx版跑起来了，也把前端挂载进docker了，然后跑起来前端的mind-map，不管是80还是/mind-map都没有页面。。。只有一个title

得带着文件id访问，所以最好从工作台里打开

**Comment by 13653216371** [comment]
> > 后端用docker的nginx版跑起来了，也把前端挂载进docker了，然后跑起来前端的mind-map，不管是80还是/mind-map都没有页面。。。只有一个title
> 
> 得带着文件id访问，所以最好从工作台里打开

后端在docker跑，前端html挂载进去，然后前端的各个组件单独运行起来，这样是不是不行啊？

**Comment by 13653216371** [comment]
> > 后端用docker的nginx版跑起来了，也把前端挂载进docker了，然后跑起来前端的mind-map，不管是80还是/mind-map都没有页面。。。只有一个title
> 
> 怎么把前端和后端一起放在docker里跑，如果有镜像可以分享下吗

目前我还没有跑起来，不清楚后端在docker，前端在宿主机，能不能跑起来

**Comment by 13653216371** [comment]
跑起来了 https://github.com/yomea/lx-doc/issues/1
